[build]
  publish = "."
  command = "echo $NETLIFY_AUTH_USERS > users.txt"

[context.production]
  environment = { NODE_VERSION = "16" }

# Password protection configuration
[auth]
  usersFilePath = "./users.txt"
