# Basic Netlify configuration
[build]
  # Publish directory (where the final, built files will be placed)
  publish = "."
  
  # Optional build command - not needed for static HTML/JS
  # command = "npm run build"

# Production environment variables
[context.production]
  environment = { NODE_VERSION = "16" }

# For SPA routing - serves index.html for any route
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200